name: Legal Consulting
favicon: null
layout_spectrum: 0.10317
typography_spectrum: 0.3870879386086017
title: Legal Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.15708133997395635
  lightness: 0.15026730671525002
  saturation: 0.11014838609844446
  rhythmicContrast: 0.8283943824935704
purpose: []
